### ISSUE TITLE
Automatically gaining achievements in new worlds

### ISSUE THREAD

**Issue by Shahelion** [yrsegal/NaturalPledge#58] opened 2018-12-18 07:14 UTC
As soon as the world has loaded, I am granted the first three achievements/advancements automatically for some reason.
 The New Millenium, The Glass of Time, and Chaining Intention.

Mod list: https://pastebin.com/06YC7rhy

**Comment by yrsegal** [comment] 2018-12-24 20:12
Duplicate of ejektaflex/NaturalPledge#14

**Closed as completed by yrsegal** 2018-12-24 20:12 UTC
